apiVersion: acme.com/v1
kind: Postgres
metadata:
  name: voting-database
---
apiVersion: acme.com/v1
kind: Workload
metadata:
  name: voting-app-backend
route: /api(/|$)(.*)
rewrite: /$2
image: wingcloudbot/vote-backend:sha-{{ .Values.revision }}
replicas: 3
port: 3000
env:
  POSTGRES_HOST: 123456
  POSTGRES_PORT: ${ref://postgres.acme.com/voting-database/port}
  POSTGRES_USER: ${ref://postgres.acme.com/voting-database/user}
  POSTGRES_DB: ${ref://postgres.acme.com/voting-database/database}
envSecrets:
  POSTGRES_PASSWORD:
    name: ${ref://postgres.acme.com/voting-database/passwordSecret}
    key: ${ref://postgres.acme.com/voting-database/passwordKey}
